import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar, { BottomNavBar } from "@/components/NavBar";
import Link from "next/link";
import { ImMobile } from "react-icons/im";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MGH Cardiovascular Associates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Providers>
          <div className="bg-primary max-md:py-2 px-2  md:h-9 w-full flex items-center justify-center text-white text-sm md:px-12">
            <div className="max-w-screen-2xl flex w-full items-center justify-between md:flex-row flex-col gap-y-1 ">
              <Link className="text-xs max-md:text-center" href={'https://maps.google.com'} target="_blank">Address: 680 Broadway, Suite No. 503, Paterson, NJ 07514</Link>
              <div className="flex flex-row gap-x-1 items-center">
                <ImMobile size={25} className="text-[#E2C08E]" />
                <Link className="text-xs max-md:text-center" href={'tel:9736535867'}>Call Us : (973) 653-5867</Link>
              </div>
            </div>
          </div>
          <div className="fixed top-6 md:top-14 w-full z-[999]">
            <NavBar />
          </div>
          {children}
          <div className="fixed bottom-6 w-full z-[999]">
            <BottomNavBar />
          </div>
        </Providers>
      </body>
    </html>
  );
}
