import AOSInit from "@/components/AOSInit";
import NavBar, { BottomNavBar } from "@/components/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ImMobile } from "react-icons/im";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MGH Cardiovascular Associates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={`${inter.className} bg-white`}>
        <Providers>
          <div className="flex w-full items-center justify-center bg-primary px-2 text-sm text-white max-md:py-2 md:h-9 md:px-12">
            <div className="flex w-full max-w-screen-2xl flex-col items-center justify-between gap-y-1 md:flex-row">
              <Link
                className="text-xs max-md:text-center"
                href={"https://www.google.com/maps"}
                target="_blank"
              >
                Address: 680 Broadway, Suite No. 503, Paterson, NJ 07514
              </Link>
              <div className="flex flex-row items-center gap-x-1">
                <ImMobile size={25} className="text-[#E2C08E]" />
                <Link
                  className="text-xs max-md:text-center"
                  href={"tel:9736535867"}
                >
                  Call Us : (973) 653-5867
                </Link>
              </div>
            </div>
          </div>
          <div className="fixed top-6 z-[999] w-full md:top-14">
            <NavBar />
          </div>
          {children}
          <div className="fixed bottom-6 z-[999] w-full">
            <BottomNavBar />
          </div>
        </Providers>
      </body>
    </html>
  );
}
